### ISSUE TITLE
Module crashes recent freeswitch (1.7 git)

### ISSUE THREAD

**Issue by nevian427** [xadhoom/mod_bcg729#4]
Hi,

Freeswitch crashes on start if module configured.
If we try load after start FS complains
2015-11-05 14:34:36.767936 [CRIT] switch_loadable_module.c:197 Failed to load codec interface G.729 from mod_bcg729 due to bytes per frame 32606 exceeding buffer size 8192.

On unloading FS crashes :(

**Comment by xadhoom** [comment]
thanks for the report.

as soon as I've some time I'll check it. 
Right now I know that on 1.6 branch works ok, need to find time to investigate.

**Comment by xadhoom** [comment]
can you try branch https://github.com/xadhoom/mod_bcg729/tree/fix_issue_4 ?
Not tested yet, bu it should be ok.

**Comment by nevian427** [comment]
I'm afraid this doesn't work :(
Same crash

**Comment by nevian427** [comment]
It crashes the same way under latest 1.6.5 from 1.6 branch :(
But users in our local users group reports about successful in prod env.
So I believe it's something local for me and need to be investigated with your help. Don't hesitate to contact me any time for any possible debug

**Comment by xadhoom** [comment]
well yes, on my systems is working ok with latest master and v1.6 branch.

what environment are you running? which version of bcg729 is being checked out?

**Comment by nevian427** [comment]
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.9 (wheezy)
Release:	7.9
Codename:	wheezy

Linux domain.russia 3.16-0.bpo.3-amd64 #1 SMP Debian 3.16.5-1~bpo70+1 (2014-11-02) x86_64 GNU/Linux

module is on master branch (also tried fix_issue_4)

On 10 Dec  2015, at 21:36, Matteo <notifications@github.com> wrote:

> well yes, on my systems is working ok with latest master and v1.6 branch.
> 
> what environment are you running? which version of bcg729 is being checked out?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
Serge S. Yuriev

**Comment by nevian427** [comment]
Forgot to mention: it's virtual enviroment under VMWare 5.5

**Comment by xadhoom** [comment]
do you mind to try under debian jessie? I don't have any debian system to
test and jessie is the preferred distro of the fs team, so maybe is some
compilator issue.

**Comment by nevian427** [comment]
Ummm..
This can be hard.. I need to discuss resources allocation with our infrastructure admins.
I'll try later this month.

Btw in our local FS users group we have success reports on Jessie.
Fairly speaking I bet on virtualization problems.

-- 
Serge via mobile

**Comment by samael33** [comment]
Same here.... 
FS 1.6.5, Jessie, VmWare env.

**Comment by nevian427** [comment]
FS 1.7 master, Jessie, VirtualBOX - work

**Comment by madovsky** [comment]
same here. FS is blocked when it encounter mod_g729 at start

**Comment by girishdharmaraj** [comment]
Any idea I am trying it on the VM environment. 

2016-05-13 06:52:34.530571 [INFO] mod_com_g729.c:254 G.729A license count => 10
2016-05-13 06:52:34.530571 [CONSOLE] switch_loadable_module.c:1538 Successfully Loaded [mod_com_g729]
2016-05-13 06:52:34.530571 **[CRIT] switch_loadable_module.c:197 Failed to load codec interface G.729 from mod_com_g729 due to bytes per frame 608487423 exceeding buffer size 8192.**
2016-05-13 06:52:34.530571 [NOTICE] switch_loadable_module.c:338 Adding API Function 'g729_count'
2016-05-13 06:52:34.530571 [NOTICE] switch_loadable_module.c:338 Adding API Function 'g729_available'
2016-05-13 06:52:34.530571 [NOTICE] switch_loadable_module.c:338 Adding API Function 'g729_info'
2016-05-13 06:52:34.530571 [INFO] mod_enum.c:880 ENUM Reloaded
2016-05-13 06:52:34.530571 [INFO] switch_time.c:1415 Timezone reloaded 530 definitions

**Comment by xadhoom** [comment]
???

you're loading the commercial g729 module from freeswitch, you should report issues to https://freeswitch.org/jira/projects/FS

**Comment by p00h** [comment]
> 2016-05-13 06:52:34.530571 [INFO] mod_com_g729.c:254 G.729A license count => 10
You're using the original module, not the compiled one)
Basically you should disable legacy module, copy the compiled one to the appropriate directory, and enable it within config
